/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <div className="flex items-center h-2/3 ">
          <video src="/video.mp4" className="h-full w-2/3" autoPlay loop muted></video>
          <div className="h-full w-1/3 bg-green-500"></div>
        </div>
        <img src="/banner.jpg" className="h-1/3 w-full"></img>
      </main>
    </>
  );
}
